config/routes.rb
Rails.application.routes.draw do
  resources :feedbacks
  resources :bookings
  get 'pages/secret'
  # Add a root route if you don't have one...
  	# We can use users#new for now, or replace this with the controller and action you want to be the site root:
  	root to: 'users#new'

    	# sign up page with form:
  	get 'users/new' => 'users#new', as: :new_user

  	# create (post) action for when sign up form is submitted:
  	post 'users' => 'users#create'

    # log in page with form:
	get '/login'     => 'sessions#new'

	# create (post) action for when log in form is submitted:
	post '/login'    => 'sessions#create'

	# delete action to log out:
	delete '/logout' => 'sessions#destroy' 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord

  validates :Quantity, inclusion: 1...3 , presence: true
  validates :Name, length: {in: 2..20}, uniqueness: true , presence: true
end

app/models/feedback.rb
class Feedback < ApplicationRecord

  has_one_attached :image

  validates :caption , presence: true
  validates :image , presence: true
end

app/models/user.rb
class User < ApplicationRecord

    has_secure_password

    validates :email , format: {with: /.*@.*/}
    validates :email , presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception


 # Make the current_user method available to views also, not just controllers:
 helper_method :current_user

 # Define the current_user method:
 def current_user
   # Look up the current user based on user_id in the session cookie:
   @current_user ||= User.find(session[:user_id]) if session[:user_id]
 end
 # authroize method redirects user to login page if not logged in:
    def authorize
      redirect_to login_path, alert: 'You must be logged in to access this page.' if current_user.nil?
    end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :authorize, only: [:index , :edit]
  before_action :set_booking, only: [:show, :edit, :update, :destroy]

  # GET /bookings
  # GET /bookings.json
  def index
    @bookings = Booking.all
  end

  # GET /bookings/1
  # GET /bookings/1.json
  def show
  end

  # GET /bookings/new
  def new
    @booking = Booking.new
  end

  # GET /bookings/1/edit
  def edit
  end

  # POST /bookings
  # POST /bookings.json
  def create
    @booking = Booking.new(booking_params)

    respond_to do |format|
      if @booking.save
        format.html { redirect_to @booking, notice: 'Booking was successfully created.' }
        format.json { render :show, status: :created, location: @booking }
      else
        format.html { render :new }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bookings/1
  # PATCH/PUT /bookings/1.json
  def update
    respond_to do |format|
      if @booking.update(booking_params)
        format.html { redirect_to @booking, notice: 'Booking was successfully updated.' }
        format.json { render :show, status: :ok, location: @booking }
      else
        format.html { render :edit }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookings/1
  # DELETE /bookings/1.json
  def destroy
    @booking.destroy
    respond_to do |format|
      format.html { redirect_to bookings_url, notice: 'Booking was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_booking
      @booking = Booking.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def booking_params
      params.require(:booking).permit(:Name, :check_in, :check_out, :Quantity)
    end
end

app/controllers/feedbacks_controller.rb
class FeedbacksController < ApplicationController
  before_action :authorize, only: [:index , :edit]
  before_action :set_feedback, only: [:show, :edit, :update, :destroy]

  # GET /feedbacks
  # GET /feedbacks.json
  def index
    @feedbacks = Feedback.all
  end

  # GET /feedbacks/1
  # GET /feedbacks/1.json
  def show
  end

  # GET /feedbacks/new
  def new
    @feedback = Feedback.new
  end

  # GET /feedbacks/1/edit
  def edit
  end

  # POST /feedbacks
  # POST /feedbacks.json
  def create
    @feedback = Feedback.new(feedback_params)

    respond_to do |format|
      if @feedback.save
        format.html { redirect_to @feedback, notice: 'Feedback was successfully created.' }
        format.json { render :show, status: :created, location: @feedback }
      else
        format.html { render :new }
        format.json { render json: @feedback.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /feedbacks/1
  # PATCH/PUT /feedbacks/1.json
  def update
    respond_to do |format|
      if @feedback.update(feedback_params)
        format.html { redirect_to @feedback, notice: 'Feedback was successfully updated.' }
        format.json { render :show, status: :ok, location: @feedback }
      else
        format.html { render :edit }
        format.json { render json: @feedback.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /feedbacks/1
  # DELETE /feedbacks/1.json
  def destroy
    @feedback.destroy
    respond_to do |format|
      format.html { redirect_to feedbacks_url, notice: 'Feedback was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_feedback
      @feedback = Feedback.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def feedback_params
      params.require(:feedback).permit(:Optional_Name, :caption , :image)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  # Restrict access so only logged in users can access the secret page:
    before_action :authorize, only: [:secret]

  def secret
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
   # No need for anything in here, we are just going to render our
   # new.html.erb AKA the login page
 end

 def create
   # Look up User in db by the email address submitted to the login form and
   # convert to lowercase to match email in db in case they had caps lock on:
   user = User.find_by(email: params[:login][:email].downcase)

   # Verify user exists in db and run has_secure_password's .authenticate()
   # method to see if the password submitted on the login form was correct:
   if user && user.authenticate(params[:login][:password])
     # Save the user.id in that user's session cookie:
     session[:user_id] = user.id.to_s
     redirect_to pages_secret_path, notice: 'Successfully logged in!'
   else
     # if email or password incorrect, re-render login page:
     flash.now.alert = "Incorrect email or password, try again."
     render :new
   end
 end

 def destroy
   # delete the saved user_id key/value from the cookie:
   session.delete(:user_id)
   redirect_to login_path, notice: "Logged out!"
 end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    # store all emails in lowercase to avoid duplicates and case-sensitive login errors:
    @user.email.downcase!

    if @user.save
      # If user saves in the db successfully:
      flash[:notice] = "Account created successfully!"
      redirect_to root_path
    else
      # If user fails model validation - probably a bad password or duplicate email:
      flash.now.alert = "Oops, couldn't create account. Please make sure you are using a valid email and password and try again."
      render :new
    end
  end

private

  def user_params
    # strong parameters - whitelist of allowed fields #=> permit(:name, :email, ...)
    # that can be submitted by a form to the user model #=> require(:user)
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bookings/_form.html.erb
<%= form_with(model: booking, local: true) do |form| %>
  <% if booking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(booking.errors.count, "error") %> prohibited this booking from being saved:</h2>

      <ul>
      <% booking.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Name %>
    <%= form.text_field :Name %>
  </div>

  <div class="field">
    <%= form.label :check_in %>
    <%= form.datetime_select :check_in %>
  </div>

  <div class="field">
    <%= form.label :check_out %>
    <%= form.datetime_select :check_out %>
  </div>

  <div class="field">
    <%= form.label :Quantity %>
    <%= form.number_field :Quantity %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/bookings/edit.html.erb
<h1>Editing Booking</h1>

<%= render 'form', booking: @booking %>

<%= link_to 'Show', @booking %> |
<%= link_to 'Back', bookings_path %>

app/views/bookings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bookings</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Check in</th>
      <th>Check out</th>
      <th>Quantity</th>
      <th colspan="3"></th>
      <th> <%= link_to 'Back to Homepage' ,  pages_secret_path %> </th>
    </tr>
  </thead>

  <tbody>
    <% @bookings.each do |booking| %>
      <tr>
        <td><%= booking.Name %></td>
        <td><%= booking.check_in %></td>
        <td><%= booking.check_out %></td>
        <td><%= booking.Quantity %></td>
        <td><%= link_to 'Show', booking %></td>
        <td><%= link_to 'Edit', edit_booking_path(booking) %></td>
        <td><%= link_to 'Destroy', booking, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Booking', new_booking_path %>

app/views/bookings/new.html.erb
<h1>New Booking</h1>

<%= render 'form', booking: @booking %>

<%= link_to 'Back', bookings_path %>

app/views/bookings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @booking.Name %>
</p>

<p>
  <strong>Check in:</strong>
  <%= @booking.check_in %>
</p>

<p>
  <strong>Check out:</strong>
  <%= @booking.check_out %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @booking.Quantity %>
</p>

<%= link_to 'Edit', edit_booking_path(@booking) %> |
<%= link_to 'Back', bookings_path %>

app/views/feedbacks/_form.html.erb
<%= form_with(model: feedback, local: true) do |form| %>
  <% if feedback.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(feedback.errors.count, "error") %> prohibited this feedback from being saved:</h2>

      <ul>
      <% feedback.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Optional_Name %>
    <%= form.text_field :Optional_Name %>
  </div>

  <div class="field">
    <%= form.label  :image %>
    <%= form.file_field :image %>
  </div>

  <div class="field">
    <%= form.label :caption %>
    <%= form.text_area :caption %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/feedbacks/edit.html.erb
<h1>Editing Feedback</h1>

<%= render 'form', feedback: @feedback %>

<%= link_to 'Show', @feedback %> |
<%= link_to 'Back', feedbacks_path %>

app/views/feedbacks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Feedbacks</h1>

<table>
  <thead>
    <tr>
      <th>Optional name</th>
      <th>Caption</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @feedbacks.each do |feedback| %>
      <tr>
        <td><%= feedback.Optional_Name %></td>
        <td><%= feedback.caption %></td>
        <td><%= link_to 'Show', feedback %></td>
        <td><%= link_to 'Edit', edit_feedback_path(feedback) %></td>
        <td><%= link_to 'Destroy', feedback, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Feedback', new_feedback_path %>

app/views/feedbacks/new.html.erb
<h1>New Feedback</h1>

<%= render 'form', feedback: @feedback %>

<%= link_to 'Back', pages_secret_path %>

app/views/feedbacks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Optional name:</strong>
  <%= @feedback.Optional_Name %>
</p>

<div style ="width:400px; height:auto">
<%= link_to image_tag(@feedback.image , style:'width:100%'),feedback_path %>
</div>

<p>
  <strong>Caption:</strong>
  <%= @feedback.caption %>
</p>

<%= link_to 'Edit', edit_feedback_path(@feedback) %> |
<%= link_to 'Back', feedbacks_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pass</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if current_user %>
      <!-- current_user will return true if a user is logged in -->
      <%= "Logged in as #{current_user.email}" %> | <%= link_to 'Home', pages_secret_path %> | <%= link_to 'Log Out', logout_path, method: :delete %>
    <% else %>
      <!-- not logged in -->
      <%= link_to 'Home', root_path %> | <%= link_to 'Log In', login_path %> or <%= link_to 'Sign Up', new_user_path %>
    <% end %>
    <hr>
    <% if notice %>
      	    <%= notice %>
	<% end %>

	<% if alert %>
      	    <%= alert %>
	<% end %>
    <%= yield %>
  </body>
</html>

app/views/pages/secret.html.erb
<h1 align="center"> Tipids Hotel</h1>
<p align="center" >Nakakamura ka Dito</p>


<%= link_to 'Book a room' , bookings_path %>
<%= link_to 'Give us a feedback' , new_feedback_path %> 

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name, autofocus: true %>
  </div>
  <div>
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  <div>
    <%= f.submit "Sign up!" %>
  </div>
<% end %>